# Generated by Django 4.2.5 on 2023-09-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_alter_universityinfo_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityinfo',
            options={'ordering': ['-id']},
        ),
    ]
