# Generated by Django 4.2.5 on 2023-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0003_alter_universityinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityinfo',
            options={'ordering': ['id']},
        ),
    ]
